import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Xponent Tribe",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <meta
        name="google-site-verification"
        content="74EGKQRJa4PSDnhhnhTZBm3A_SKTdLOUf4UiiGtU9Uk"
      />
      <body className={inter.className}>{children}</body>
    </html>
  );
}
